# Generated by Django 6.0.2 on 2026-03-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200, verbose_name='Nombre de la actividad')),
                ('grade_type', models.CharField(choices=[('exam', 'Examen'), ('quiz', 'Quiz'), ('homework', 'Tarea'), ('project', 'Proyecto'), ('participation', 'Participación'), ('activity', 'Actividad'), ('other', 'Otro')], default='activity', max_length=20, verbose_name='Tipo')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota')),
                ('max_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=4, verbose_name='Nota máxima')),
                ('period', models.CharField(blank=True, max_length=50, verbose_name='Periodo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-date'],
            },
        ),
    ]
