# Generated by Django 6.0.5 on 2026-06-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_alter_grade_student_alter_subject_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='period',
            field=models.CharField(blank=True, choices=[('Periodo I', 'Periodo I'), ('Periodo II', 'Periodo II'), ('Periodo III', 'Periodo III')], max_length=50, verbose_name='Periodo'),
        ),
    ]
