# Generated by Django 6.0.5 on 2026-06-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_alter_grade_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('exam', 'Examen'), ('quiz', 'Quiz'), ('homework', 'Tarea'), ('workshop', 'Taller'), ('project', 'Proyecto'), ('participation', 'Participación'), ('activity', 'Actividad'), ('other', 'Otro')], default='activity', max_length=20, verbose_name='Tipo'),
        ),
    ]
