# Generated by Django 6.0.5 on 2026-05-16 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['created_at'], 'verbose_name': 'Historial de Chat', 'verbose_name_plural': 'Historiales de Chat'},
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='Resumen compacto de la conversación generado por IA')),
                ('messages_covered', models.IntegerField(default=0, help_text='Cantidad de mensajes cubiertos por este resumen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resumen de Conversación',
                'verbose_name_plural': 'Resúmenes de Conversación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_grade', models.CharField(blank=True, default='', help_text="Grado(s) que enseña, ej: '3° de primaria'", max_length=50)),
                ('subjects', models.CharField(blank=True, default='', help_text="Materias que enseña, ej: 'Matemáticas, Lenguaje'", max_length=200)),
                ('teaching_style', models.TextField(blank=True, default='', help_text='Estilo de enseñanza preferido')),
                ('preferred_activities', models.TextField(blank=True, default='', help_text='Tipos de actividades que prefiere')),
                ('school_context', models.TextField(blank=True, default='', help_text='Contexto escolar relevante (rural/urbano, recursos, etc.)')),
                ('additional_notes', models.TextField(blank=True, default='', help_text='Notas adicionales sobre el perfil pedagógico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memoria de Usuario',
                'verbose_name_plural': 'Memorias de Usuario',
            },
        ),
    ]
